"""add mailboxes emails and email chunks

Revision ID: 2066068f8f06
Revises: 39d2b66d442c
Create Date: 2026-09-25 17:03:55.964514

"""
from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2066068f8f06'
down_revision: str | Sequence[str] | None = '39d2b66d442c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailboxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('yahoo', 'gmail')", name='ck_mailboxes_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'address', name='uq_mailboxes_provider_address')
    )
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('folder', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('from_address', sa.Text(), nullable=False),
    sa.Column('to_addresses', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=32), server_default='fyi', nullable=False),
    sa.Column('newsletter_source', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("label IN ('needs_reply', 'promotional', 'newsletter', 'invoice', 'fyi', 'ai_newsletter')", name='ck_emails_label'),
    sa.CheckConstraint("newsletter_source IS NULL OR newsletter_source IN ('tldr', 'alpha_signal')", name='ck_emails_newsletter_source'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox_id', 'message_id', name='uq_emails_mailbox_message_id')
    )
    op.create_index('ix_emails_from_address', 'emails', ['from_address'], unique=False)
    op.create_index('ix_emails_mailbox_label_sent_at', 'emails', ['mailbox_id', 'label', sa.literal_column('sent_at DESC')], unique=False)
    op.create_table('email_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id', 'chunk_index', name='uq_email_chunks_email_index')
    )
    op.create_index('ix_email_chunks_embedding_hnsw', 'email_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_email_chunks_search_vector', 'email_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_chunks_search_vector', table_name='email_chunks', postgresql_using='gin')
    op.drop_index('ix_email_chunks_embedding_hnsw', table_name='email_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('email_chunks')
    op.drop_index('ix_emails_mailbox_label_sent_at', table_name='emails')
    op.drop_index('ix_emails_from_address', table_name='emails')
    op.drop_table('emails')
    op.drop_table('mailboxes')
    # ### end Alembic commands ###
