"""add chat thread agent

Revision ID: 39d2b66d442c
Revises: 94205518dcb7
Create Date: 2026-09-25 15:21:15.191439

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39d2b66d442c"
down_revision: str | Sequence[str] | None = "94205518dcb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_threads",
        sa.Column(
            "agent", sa.String(length=32), server_default="documents", nullable=False
        ),
    )
    op.create_check_constraint(
        "ck_chat_threads_agent",
        "chat_threads",
        "agent IN ('documents', 'email')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_chat_threads_agent", "chat_threads", type_="check")
    op.drop_column("chat_threads", "agent")
    # ### end Alembic commands ###
