"""add email from_name

Revision ID: 5a471474ec22
Revises: ec52ad5d7695
Create Date: 2026-10-07 19:04:20.623481

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a471474ec22'
down_revision: str | Sequence[str] | None = 'ec52ad5d7695'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('from_name', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'from_name')
    # ### end Alembic commands ###
