"""add email citations

Revision ID: 6459ddacd6e8
Revises: 8334bab3a806
Create Date: 2026-09-30 10:52:44.776013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6459ddacd6e8'
down_revision: Union[str, Sequence[str], None] = '8334bab3a806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('email_chunk_id', sa.UUID(), nullable=True),
    sa.Column('news_item_id', sa.UUID(), nullable=True),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(email_chunk_id IS NOT NULL) <> (news_item_id IS NOT NULL)', name='ck_email_citations_one_target'),
    sa.ForeignKeyConstraint(['email_chunk_id'], ['email_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'citation_index', name='uq_email_citations_message_index')
    )
    op.create_index('ix_email_citations_email_chunk_id', 'email_citations', ['email_chunk_id'], unique=False)
    op.create_index('ix_email_citations_message_id', 'email_citations', ['message_id'], unique=False)
    op.create_index('ix_email_citations_news_item_id', 'email_citations', ['news_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_citations_news_item_id', table_name='email_citations')
    op.drop_index('ix_email_citations_message_id', table_name='email_citations')
    op.drop_index('ix_email_citations_email_chunk_id', table_name='email_citations')
    op.drop_table('email_citations')
    # ### end Alembic commands ###
