"""add news stories

Revision ID: 8334bab3a806
Revises: 1605b484a9b9
Create Date: 2026-09-28 14:19:52.518097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8334bab3a806"
down_revision: Union[str, Sequence[str], None] = "1605b484a9b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_stories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("is_big", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("news_items", sa.Column("story_id", sa.UUID(), nullable=True))
    op.create_index("ix_news_items_story_id", "news_items", ["story_id"], unique=False)
    op.create_foreign_key(
        "fk_news_items_story_id",
        "news_items",
        "news_stories",
        ["story_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_news_items_story_id", "news_items", type_="foreignkey")
    op.drop_index("ix_news_items_story_id", table_name="news_items")
    op.drop_column("news_items", "story_id")
    op.drop_table("news_stories")
    # ### end Alembic commands ###
