"""add job runs

Revision ID: 9c8e4850a3a6
Revises: ba98a3ea5b4f
Create Date: 2026-10-08 17:43:16.471470

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c8e4850a3a6'
down_revision: str | Sequence[str] | None = 'ba98a3ea5b4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# RLS with no policies: the anon key reads nothing; the backend's service role bypasses RLS.
RLS_TABLES = ("job_runs",)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'ok', 'failed')", name='ck_job_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_job_started_at', 'job_runs', ['job', 'started_at'], unique=False)
    # ### end Alembic commands ###
    for table in RLS_TABLES:
        op.execute(f'ALTER TABLE public."{table}" ENABLE ROW LEVEL SECURITY')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_runs_job_started_at', table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
